# Generated by Django 4.2.6 on 2023-10-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderName', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=100000)),
                ('photo', models.ImageField(upload_to='Order')),
                ('barcode_id', models.IntegerField(default=0)),
            ],
        ),
    ]
